FROM docker.io/library/ubuntu:22.04@sha256:2edbbc5dc405e9612ba3584ce95480277e3eb374407b5505fe26f17df77c7dbc

RUN apt-get -y update
RUN apt-get -y install clang-format-14
RUN ln -s /bin/clang-format-14 /bin/clang-format

USER 1000
WORKDIR /tetragon

ENTRYPOINT ["clang-format"]
CMD ["--help"]
