FROM curlimages/curl:8.00.1@sha256:9e886c104cae1072f7874c9c214f77c6758f2e8a477234e32eda5fcbfa41f225 AS downloader
ARG HUGO_VERSION=0.111.3
ARG TARGETARCH
WORKDIR tmp
RUN curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-${TARGETARCH}.tar.gz | tar xz

# Hugo extended is dynamically linked
FROM golang:1.23.2@sha256:ad5c126b5cf501a8caef751a243bb717ec204ab1aa56dc41dc11be089fafcb4f
# create an unprivileged user to run hugo
RUN mkdir -p /var/hugo && \
    addgroup --system --gid 1000 hugo && \
    adduser --system --gecos hugo --uid 1000 --home /var/hugo hugo && \
    chown -R hugo /var/hugo && \
    runuser -u hugo -- git config --global --add safe.directory /src
COPY --from=downloader /tmp/hugo /usr/local/bin/hugo
WORKDIR /src

USER hugo:hugo
EXPOSE 1313
ENTRYPOINT ["/usr/local/bin/hugo"]
CMD ["--help"]

